version: '1.0'
name: 'reverts-rails'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=reverts_rails
      - POSTGRES_PASSWORD=reverts
      - POSTGRES_DB=reverts_rails_development
    ports:
      - '5432:5432'
    volumes:
      - psql-data:/var/lib/postgresql/data
  postgres-test:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=reverts_rails
      - POSTGRES_PASSWORD=reverts
      - POSTGRES_DB=reverts_rails_test
    ports:
      - '5433:5432'
volumes:
  psql-data:
    driver: local
